RTSPSource:
  reconnect: true
  reconnect_interval_ms: 3000
  transport: tcp
  timeout_ms: 10000

NvidiaDecode:
  gpu_id: 0

NvidiaEncode:
  gpu_id: 0
  fps: 30

RTSPPublish:
  reconnect: true
  reconnect_interval_ms: 3000
  transport: tcp
  timeout_ms: 10000
  packet_size: 1452

YoloDetect:
  classes: [2]
  confidence: 0.25
  gpu_id: 0
  inference_interval_frame: 1

BoxOverlay:
  line_width: 2
  line_color: "#00ff00"
  keep_previous: true
